### ISSUE TITLE
window.originalPostMessage  is not found?  What is the host environment?

### ISSUE THREAD

**Issue by raisezhang** [coinjinja/coinview-js-sdk#1]
RT， Thanks ~

**Comment by ITJesse** [comment]
Could you please provide more information about the environment you are testing?

**Comment by raisezhang** [comment]
Tested in chrome browser， Or have related documents to refer to， Thanks

**Comment by ITJesse** [comment]
You have to test your code in CoinView app.
You can download it from App Store for iPhone or Play Store for Android.

**Comment by raisezhang** [comment]
I downloaded the app, but I still can't find a way to use this SDK. 
For example, there should be a list of open platform products?  but I didn't find it.

**Comment by ITJesse** [comment]
You can check this page:
https://www.coinjinja.com/coinview-sdk

**Comment by raisezhang** [comment]
Thanks   @ITJesse
